##############################################################################
#
#    file                 : Makefile
#    created              : Sun Feb 13 17:46:19 CET 2000
#    copyright            : (C) 2000, 2013 by Eric Espie, Bernhard Wymann                         
#    email                : berniw@bluewin.ch
#    version              : $Id: Makefile,v 1.1.2.1 2013/11/13 08:55:41 berniw Exp $                                  
#
##############################################################################
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
##############################################################################


DATADIR    = tracks/road/e-track-2

DATA   = e-track-2.xml e-track-2.acc readme.txt 01.png 02.png ALAUBM.png asphalt-e2.png asphalt-pit-e2.png \
	asphalt-sl-e2.png asphalt-tile-e2.png asphalt-tile-stripes-e2.png asphalt-white-tile.png background.png \
	back-sign.png barrier-1.png barrier-2.png block4f.png block4s.png block5-arbor_n.png block5f.png \
	block5fqa.png block5s.png block5t.png border2m.png border-grass-e2.png border-grass-end-e2.png \
	border-grass-start-e2.png border-gravel-e2.png border-gravel-end-e2.png border-gravel-start-e2.png \
	bordertile.png BUS.png CAMPER01.png CAMPER02.png CAMPER3.png CAMPER41.png CAMPER4.png CAR01.png \
	CAR02.png CAR05.png CAR06.png CHtree_n.png CMNTA.png CMNTBB.png CMNTB.png conc.png concrete-wall1.png \
	CONCTP.png curb-red-white-e2.png e-track-2.png fence_arbor_n.png FNCEB.png GBtree_n.png GEtree_n.png \
	grass-bw-d2.png grass-cut-e2.png grass-dirt-e2.png grass-e2.png grass-end-e2.png grass-start-e2.png \
	gravel-e2.png gravel-end-e2.png gravel-start-e2.png GSPAtree.png house16roof.png house17base.png \
	house17concrete.png house17elevator.png house17facade.png house17roof.png house18chimney.png \
	house18facade.png house18top.png house20facade.png house21w1.png house21w2.png house22base.png \
	house22facade.png house23facade.png house24brick.png house24facade.png house24roof.png \
	house24timber2.png house24timber.png house25ch.png house25chtop.png house25elevator.png \
	house25facade.png house25roof.png house25side.png house26base.png house26ceil.png house26elev.png \
	house26facade.png house26parking.png house27facade.png house27r1.png house27r2.png house27side.png \
	house28facade.png house31facade.png house31roof.png house32facade.png house32roof.png house33facade.png \
	house33side.png house34facade.png house34roof.png house35facade.png house36facade.png improveyou-wall.png \
	IYtree_n.png LAMAOP.png	MASE01.png MASE02.png mycast.png PASS10.png PASS3.png PASS4.png PDKKA13.png \
	PITWB.png pylon1.rgb pylon2.rgb pylon3.rgb raceline.png road-dirt.png road-e2.png rock1-e2.png \
	rock-wall-e2.png shadow2.png shadow2.rgb STAIRSD.png STAIRS.png tent2.png tire-wall-at.png \
	tire-wall-green.png tire-wall-se.png tire-wall-ur.png toilette.png TOPCROWD.png tree11_n.png \
	tree18end_n.png tree18_n.png tree18side1_n.png tree18side2_n.png tree7_n.png tree9_n.png tree_eva_n.png \
	treefc_n.png TreeRNS3.png TreeRNS4.png TreeRNS5.png treeS3_n.png treeUGLIES01_n.png treeUGLIES02_n.png \
	TRIBA08.png TRIBA11.png TRIBB01.png TRIBB02.png TRIBB03.png turn100.png turn200.png turn25.png \
	turn300.png turn50.png

data-tracks-road_PKGFILES	= $(DATA)

data-tracks-road_PKGDIR	= $(DATADIR)

include ${MAKE_DEFAULT}



