##############################################################################
#
#    file                 : Makefile
#    created              : Sat Mai 20 17:12:55 CET 2006
#    copyright            : (C) 2006 by Bernhard Wymann
#    email                : berniw@bluewin.ch
#    version              : $Id: Makefile,v 1.1.2.1 2013/09/14 22:46:36 berniw Exp $
#
##############################################################################
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
##############################################################################

TRACK     = Ushite-city

DATADIR   = tracks/road/$(TRACK)

DATA      = pylon1.rgb pylon2.rgb pylon3.rgb 1.rgb 2.rgb 3.rgb arch-g1SD-poutre1.rgb asphalt-tr-asphalt-l_nmm.rgb background.png barrier-armco2_arbor.rgb billboard-all-tune.rgb billboard-alp-torcs.rgb border-1.rgb building2.rgb building3.rgb generato-city_city.ac generato-city_city-elevation.png generato-city_city-object-map.png pattern.xml side-concdal.rgb terrain-maingrandstand.rgb Ushite-city.png Ushite-city.xml replace_side.png replace_middle.png black.png generato-city_city_replace_side.ac generato-city_city_replace_middle.ac

data-tracks-road_PKGFILES	= $(DATA)

data-tracks-road_PKGDIR	= $(DATADIR)

include ${MAKE_DEFAULT}


